version: "3.8"
name: 'spring-boot-microservices-course'
services:
  catalog-db:
    image: 'postgres:16-alpine'
    container_name: 'catalog-db'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'catalog'
    ports:
      - '15432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '500M'
        reservations:
          cpus: '0.05'
          memory: '128M'
#    networks:
#      - 'spring-boot-microservices-course-network'
#    volumes:
#      - 'catalog-db-data:/var/lib/postgresql/data'